### ISSUE TITLE
Suggestion on Room Presence

### ISSUE THREAD

**Issue by Cesarsk** [seangreen2/home_assistant#3]
Hey dude, great Room Presence System with the Google Home.

I'm new to HA but I'm trying to setup my Google home for (almost) the same purpose. But I can't really understand whether they killed Google Home support and cannot be used anymore for that.

If so, do you think I could use an Android Device as Tracker? How? I could use my previous android with Bluetooth LE to track whether I'm in the Room or not.

Nice work dude, really, I'm going to follow your work.

**Comment by seangreen2** [comment]
Unfortunately the Google Home integration does not work at all anymore. Had to rethink how I wanted room detection to be determined differently as a result.

**Comment by Cesarsk** [comment]
That's a bummer, it would've been great! 

Do you have an idea on how to use an old android device for tracking?

**Comment by seangreen2** [comment]
That I don't know aside from perhaps using Raspberry Pis and Bluetooth to accomplish the same thing I attempted to use the Homes with.

**Comment by marcusds** [comment]
Hi, I know this is an old closed ticket. 

But are you sure you aren't able to still use the Google Home for bluetooth presence detection? I used this guide https://rithvikvibhu.github.io/GHLocalApi/ and was able to scan for and see my Bluetooth devices.

**Comment by seangreen2** [comment]
I'm sure it detects devices just fine, but the Home Assistant integration as far as I know has been deprecated and no longer an integration. If you're able to get that data into Home Assistant I'm sure many people would like to know how.
