### ISSUE TITLE
living room occupancy

### ISSUE THREAD

**Issue by harphere** [seangreen2/home_assistant#4]
Hi Sean, love the detailed write up. I've been reading it off and on for a while now until I could gain some confidence in writing up something similar for myself.

One of the pains I have is in my living room, when sitting still, say reading or on the PC/phone, lights go off because no motion was sensed. How do you overcome that? Do you always have your living room TV on and playing?

**Comment by seangreen2** [comment]
I use input booleans. After being triggered they stay on permanently unless something is triggered in another room. 

My systems treats every room as the next long term location until another room triggers and then a timer begins unless the present room activity retriggers and restarts the process.

Sometimes there are false positives, but it's rare for our lifestyle.

**Comment by harphere** [comment]
Please excuse my ignorance on this next question, I'm still new to this stuff.
Why do you use multiple triggers for the living room? Wouldn't the motion sensor group be enough to mark you as in the room?
